//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Национальная_деревня
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int Id { get; set; }
        public Nullable<int> Id_посетителя { get; set; }
        public Nullable<int> id_билета { get; set; }
        public Nullable<int> количество_билетов { get; set; }
        public Nullable<int> итоговая_стоимость { get; set; }
        public Nullable<int> id_excursion { get; set; }
    
        public virtual Билеты Билеты { get; set; }
        public virtual Посетители Посетители { get; set; }
        public virtual Расписание Расписание { get; set; }
    }
}
