//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Национальная_деревня
{
    using System;
    using System.Collections.Generic;
    
    public partial class Посетители
    {
        public Посетители()
        {
            this.Заказ = new HashSet<Заказ>();
        }
    
        public int Id { get; set; }
        public string ФИО { get; set; }
        public string номер { get; set; }
        public string почта { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string фото { get; set; }
    
        public virtual ICollection<Заказ> Заказ { get; set; }
    }
}
